---
title: "LOBO CONTINUOUS MONITORING"
output: 
  flexdashboard::flex_dashboard:
  logo: www/tarponlogo.png
social: menu
source_code: "https://github.com/tbep-tech/piney-point"
runtime: shiny
css: styles.css
---
  
```{r setup, include=F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)

# libraries
library(flexdashboard)
library(tidyverse)
library(shiny)
library(patchwork)
library(stargazer)
library(plotly)
library(mapview)
library(sf)
library(leaflet)
library(WtRegDO)
library(shinyWidgets)

source('R/funcs.R')

# data
load(url('https://tbep-tech.github.io/piney-point/data/lobodat.RData'))
load(url('https://tbep-tech.github.io/piney-point/data/loboeco.RData'))

# log
log <- readLines('https://tbep-tech.github.io/piney-point/logs/lobolog.txt')

# variables to select
vrs <- list(
  `Salinity (psu)` = 'Sal', 
  `Water temp (C)` = 'Temp', 
  `CO2 (ppm)` = 'co2', 
  `DO (ml/L)` = 'DO_obs', 
  `pH` = 'ph',
  `PAR (um/m2/s)` = 'par',
  `Tide (dbar)` = 'Tide',
  `Air temp (C)` = 'ATemp', 
  `Air pressure (mb)` = 'BP',
  `Wind speed (m/s)` = 'WSpd'
)

buoylat <- 27.6594677
buoylng <- -82.6043877

# event start, stop
evnts <- lobodat %>% 
  filter(evnt) %>% 
  pull(DateTimeStamp) %>% 
  range

# date range on input data
dtrng <- range(lobodat$DateTimeStamp) %>% 
  as.Date

datsmt <- lobodat %>% 
  mutate_if(is.numeric, function(x){
    stats::filter(x, rep(1 / 24, 24), sides = 1)
  })
lobodat <- full_join(lobodat, datsmt, by = 'DateTimeStamp') %>% 
  rename_if(grepl('\\.x$', names(.)), function(x){
    gsub('\\.x$', '', x)
  }) %>% 
  rename_if(grepl('\\.y$', names(.)), function(x){
    gsub('\\.y$', '_smth', x)
  })
```

```{r reactives}
# data selection
datsel <- reactive({
  
  # inputs
  varsel1 <- input$varsel1
  varsel2 <- input$varsel2
  dtsel <- input$dtsel

  varsel1smth <- paste0(varsel1, '_smth')
  varsel2smth <- paste0(varsel2, '_smth')
  
  dat <- lobodat %>% 
    select(DateTimeStamp, !!varsel1, !!varsel2, !!varsel1smth, !!varsel2smth) %>% 
    filter(as.Date(DateTimeStamp) >= dtsel[1] & as.Date(DateTimeStamp) <= dtsel[2]) %>% 

  return(out)
  
})

# ecometab data selection
ecosel <- reactive({
  
  # inputs
  dtsel <- input$dtsel
  
  out <- loboeco %>% 
    filter(as.Date(Date) >= dtsel[1] & as.Date(Date) <= dtsel[2])

  return(out)
  
})

# time series and scatter plot
tsplo <- reactive({
  
  # inputs
  varsel1 <- input$varsel1
  varsel2 <- input$varsel2
  addobs <- input$addobs
  addtrn <- input$addtrn
  dtsel <- input$dtsel
  datsel <- datsel()

  # dtsel to posix for coord_cartesian
  dtsel <- as.POSIXct(c(dtsel[1], dtsel[2] + 1), tz = attr(datsel$DateTimeStamp, 'tzone'))
  
  lb1 <- names(vrs)[which(unlist(vrs) == varsel1)]
  lb2 <- names(vrs)[which(unlist(vrs) == varsel2)]

  lncol <- 'black'
  if(!addobs)
    lncol <- NA
  
  # y text location
  ytxt <- max(datsel[, varsel1], na.rm = T)

  p1 <- ggplot(datsel, aes_string(x = 'DateTimeStamp', y = varsel1)) + 
    geom_line(color = lncol) + 
    # geom_point() + 
    annotate('rect', xmin = evnts[1], xmax = evnts[2], ymin = -Inf, ymax = Inf, fill = 'orange', alpha = 0.2) +
    annotate('text', x = evnts[1] + 2e4, y = ytxt, hjust = 0, label = 'Active discharge', color = 'orange', size = 5) +
    coord_cartesian(xlim = dtsel) + 
    theme_minimal(base_size = 16) + 
    labs(y = lb1) + 
    theme(
      axis.title.x = element_blank()
    )
  
  p2 <- ggplot(datsel, aes_string(x = 'DateTimeStamp', y = varsel2)) + 
    geom_line(color = lncol) + 
    # geom_point() + 
    annotate('rect', xmin = evnts[1], xmax = evnts[2], ymin = -Inf, ymax = Inf, fill = 'orange', alpha = 0.2) +
    coord_cartesian(xlim = dtsel) + 
    theme_minimal(base_size = 16) + 
    labs(y = lb2) + 
    theme(
      axis.title.x = element_blank()
    )
  
  p3 <- ggplot(datsel, aes_string(x = varsel1, y = varsel2))+ 
    geom_point()+ 
    theme_minimal(base_size = 16) + 
    labs(x = lb1, y = lb2) + 
    geom_smooth(method = 'lm')
  
  # add smooth trend line
  if(addtrn){
    
    p1 <- p1 + 
      geom_line(aes_string(y = paste0(varsel1, '_smth')), color = 'tomato1', size = 1)
    
    p2 <- p2 + 
      geom_line(aes_string(y = paste0(varsel2, '_smth')), color = 'tomato1', size = 1)
    
  }
  
  p <- (p1 / p2) | p3
  
  return(p)
  
})

# ecometab plot
ecoplo <- reactive({
  
  # input
  ecosel <- ecosel()
  dtsel <- input$dtsel
  
  # y text location
  ytxt <- max(ecosel[, -1], na.rm = T)
  
  out <- plot(ecosel, by = 'days') + 
    annotate('rect', xmin = as.Date(evnts[1]), xmax = as.Date(evnts[2]), ymin = -Inf, ymax = Inf, fill = 'orange', alpha = 0.2) +
    annotate('text', x = as.Date(evnts[1]) + 0.2, y = ytxt, hjust = 0, label = 'Active discharge', color = 'orange', size = 5) +
    coord_cartesian(xlim = dtsel) + 
    theme_bw(base_size = 20)

  return(out)
  
})

# linear mod
lmstat <- reactive({
  
  # inputs
  varsel1 <- input$varsel1
  varsel2 <- input$varsel2
  datsel <- datsel()

  frm <- paste(varsel2, varsel1, sep = '~') %>% 
    as.formula
  
  out <- lm(frm, datsel)
  
  return(out)
  
})

# pearson
corstat <- reactive({
 
  # inputs
  varsel1 <- input$varsel1
  varsel2 <- input$varsel2
  datsel <- datsel()

  corv <- cor.test(datsel[[varsel1]], datsel[[varsel2]])
  
  out <- paste0('r = ', round(corv$estimate, 2), ', p ', format.pval(corv$p.value))
  
  return(out) 
  
})

output$lmstat <- renderText(stargazer(lmstat(), type = 'html', digits = 2))
output$corstat <- renderText(corstat())

```


TIME SERIES COMPARISONS
=======================================================================
  
Column {data-width=200 .tabset .tabset-fade}
-----------------------------------------------------------------------
  
### Data selection

```{r}
column(12, 
  selectInput('varsel1', 'Select first variable:', choices = vrs, selected = vrs[4])
)

column(12, 
  selectInput('varsel2', 'Select second variable:', choices = vrs, selected = vrs[5])
)

column(12, 
  sliderInput('dtsel', 'Select date range:', min = dtrng[1], max =  dtrng[2], value = dtrng, timeFormat="%Y-%m-%d")
)

column(12, 
  materialSwitch(inputId = 'addobs', label = 'Show continuous data?', value = T, width = '100%')       
)
column(12, 
  materialSwitch(inputId = 'addtrn', label = 'Add 24hr mean trend?', value = T, width = '100%')       
)

HTML('<br>')
fillCol(flex = c(NA, NA),
  column(12,
    'Regression summary:',
    uiOutput('lmstat')
  ),

  column(12, 
    'Correlation summary:', 
    uiOutput('corstat')
  ) 
  
)
```

### About


```{r}
loc <- data.frame(
  lat = buoylat,
  lon = buoylng
  ) %>% 
  st_as_sf(coords = c('lon', 'lat'), crs = 4326)

txt <- HTML('Data on this dashboard are from the <a href="http://tampabay.loboviz.com/">Tampa Bay LOBO</a> (Land/Ocean Biogeochemical Observatory) continuous monitoring buoy, located in Lower Tampa Bay. Co-located weather observations (wind, air temperature, pressure) are from <a href="http://tbports.org/">http://tbports.org/</a>, with data from station <a href="https://tidesandcurrents.noaa.gov/met.html?id=8726412">8726412</a>. All data are preliminary or provisional and are subject to revision. The data have not received final approval by the USGS and are provided on the condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from the authorized or unauthorized use of the data.  Approximate buoy location:')

m <- mapview(loc, homebutton = F, legend = F)@map %>% 
  setView(lat = buoylat, lng = buoylng, zoom = 10)

fillCol(flex = c(NA, 1), txt, m)
```


Column {.tabset .tabset-fade data-width=700}
-----------------------------------------------------------------------

### `r paste0('Data current as of ', log)`

```{r}
output$tsplo <- renderPlot(tsplo())
plotOutput('tsplo')
```

### Odum open-water metabolism

```{r}
txt <- HTML('This plot shows estimates of metabolic rates as gross production (Pg), total respiration (Rt), and net ecosystem metabolism (as the difference between the two). Metabolic rates are based on the Odum open water method (<a href="https://aslopubs.onlinelibrary.wiley.com/doi/10.4319/lo.1956.1.2.0102">Odum 1956</a>, as adapted in <a href="https://aslopubs.onlinelibrary.wiley.com/doi/full/10.1002/lom3.10062">Beck et al. 2015</a>).  Rates are shown as mmol of O<sub>2</sub> per square meter per day, assuming a well-mixed water column at an approximate depth of 5 meters.')
output$ecoplo <- renderPlot(ecoplo())
fillCol(flex = c(NA, 1), 
        txt, 
        plotOutput('ecoplo')
        )

```

