---
title: Piney Point trends synthesis
author: "MW Beck"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document
---

```{r setup, echo = FALSE, message = F, warning = F, results = 'hide'}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 9)

library(tidyverse)
library(lubridate)
library(sf)
library(ggmap)
library(ggspatial)
library(patchwork)

data(rswqdat)
data(bswqdat)
data(bsstatloc)
data(rsstatloc)
data(ppseg)
data(parms)
data(rsphydat)
data(rsphypts)
data(trnpts)
data(savtmp)
data(mcrtmp)
data(rstrnpts)

# segments
ppseg <- ppseg %>% 
  rename(area = Name) %>% 
  group_by(area) %>% 
  summarise() %>% 
  st_buffer(dist = 0.0001) %>% 
  st_buffer(dist = -0.0001) %>% 
  mutate(
    area = factor(area)
  )

cols <- c("#E16A86", "#50A315", "#009ADE")
names(cols) <- levels(ppseg$area)

# water quality plot fun
wqplo_fun <- function(rswqdat, bswqdat, ppseg, vr, cols, logtr = TRUE){

  nonbay <- c('BH01', 'P Port 2', 'P Port 3', 'PM Out', '20120409-01', 'PPC41', 'P Port 4', 'PMB01', 'NGS-S Pond')

  ##
  # wq data
  
  # monitoring data
  rswqtmp <- rswqdat %>% 
    filter(var == vr) %>% 
    filter(!station %in% nonbay) %>% 
    inner_join(rsstatloc, ., by = c('station', 'source')) %>% 
    st_intersection(ppseg) %>% 
    st_set_geometry(NULL) %>% 
    select(-qual, -bswqstation, -nrmrng, -source, -source_lng, -uni, -lbunis, -comment) %>% 
    mutate(
      date = floor_date(date, unit = 'week'), 
      mo = month(date), 
      fillcl = factor(area, levels = levels(area), labels = cols), 
      fillcl = as.character(fillcl)
      ) 
    
  # baseline data
  bswqtmp <- bswqdat %>% 
    select(-source, -uni) %>% 
    filter(var == vr) %>% 
    filter(yr > 2005 & mo %in% c(3, 4, 5)) %>% 
    inner_join(bsstatloc, ., by = 'station') %>% 
    st_intersection(ppseg) %>% 
    st_set_geometry(NULL) %>% 
    group_by(mo, var, area) %>% 
    summarise(   
      avev = mean(val, na.rm = T), 
      stdv = sd(val, na.rm = T), 
      .groups = 'drop'
    ) %>%
    left_join(parms, by = 'var') %>% 
    mutate(
      avev = round(avev, sigdig), 
      stdv = round(stdv, sigdig), 
      minv = avev - stdv, 
      minv = pmax(0, minv),
      maxv = avev + stdv,
      lbunis = gsub('^.*\\s(\\(.*\\))$', '\\1', lbs), 
      lbunis = gsub('pH', '', lbunis), 
      datestr= paste0('2021-', mo, '-01'), 
      datestr = ymd(datestr), 
      dateend = ceiling_date(datestr, unit = 'month')
    )
  
  # boxplot colors
  bxcls <- rswqtmp %>% 
    select(area, date, fillcl) %>% 
    unique
  
  ylab <- unique(rswqtmp$lbs)

  p1 <- ggplot() + 
    geom_rect(data = bswqtmp, aes(xmin = datestr, xmax = dateend, ymin = minv, ymax = maxv, group = mo, fill = 'Monthly baseline (mean +/- 1 sd'), alpha = 0.2) +
    geom_boxplot(data = rswqtmp, aes(x = date, y = val, group = date), fill= bxcls$fillcl, outlier.colour = NA, lwd = 0.75, alpha = 0.8, show.legend = F) + 
    geom_jitter(data = rswqtmp, aes(x = date, y = val, group = date), alpha = 0.4, size = 0.75) + 
    scale_fill_manual(NULL, values = 'blue') +
    scale_linetype_manual(values = 'dashed') + 
    facet_grid(area ~ ., scales = 'free_y') + 
    scale_x_date(breaks = unique(rswqtmp$date), date_labels = '%b %d', expand = c(0.1, 0.1)) +
    labs(
      y = ylab, 
      x = 'Week'
      ) + 
    coord_cartesian(xlim = range(rswqtmp$date)) +
    theme_minimal(base_size = 14) + 
    theme(
      legend.position = 'top', 
      strip.background = element_blank(), 
      strip.text = element_text(size = 14)
    )
  
  if(logtr)
    p1 <- p1 + 
      scale_y_log10(paste0('log-', ylab))
  
 out <- p1
  
 return(out)
 
}

# phyto plot fun
phyplo_fun <- function(rsphydat, rsphypts, ppseg, vr, cols){
    
  dts <- tibble(date = seq.Date(min(rsphydat$date), max(rsphydat$date), by = 'days'))
  
  # monitoring data
  toplo <- rsphydat %>% 
    inner_join(rsphypts, ., by = c('station')) %>% 
    st_intersection(ppseg) %>% 
    st_set_geometry(NULL) %>% 
    select(date, area, species) %>% 
    unique %>% 
    mutate(obs = 1) %>% 
    complete(species, date, area, fill = list(obs = 0)) %>% 
    filter(species == vr) %>% 
    arrange(area, date) %>%
    group_by(area) %>% 
    mutate(
      obs = cumsum(obs)
    )

  p1 <- ggplot(toplo, aes(x = date, y = obs, fill = area)) + 
    geom_area(alpha = 0.8) +
    scale_fill_manual(NULL, values = cols, drop = F) +
    scale_x_date(expand = c(0, 0)) + 
    theme_minimal(base_size = 14) + 
    theme(
      legend.position = 'top', 
      strip.background = element_blank(), 
      strip.text = element_text(size = 14), 
      axis.title.x = element_blank()
    ) + 
    labs(
      y = 'Cumulative observations', 
      caption = 'Observations are based on whether any station in the area recorded the taxon'
    )
  
  return(p1)
  
}
```

# {.tabset}

## Region delineation 

```{r, figh.height = 4, fig.width = 4, fig.margin = T}
##
# map

buffdist <- 0.01
northloc <- 'tr' 
scaleloc <- 'bl'

# layer extent as bbox plus buffer
dat_ext <- ppseg %>% 
  st_bbox %>% 
  st_as_sfc %>% 
  st_buffer(dist = buffdist) %>%
  st_bbox %>% 
  unname

# reference data for ggsn, MUST have geometry named column
ggsnref <- ppseg %>% 
  st_bbox %>% 
  st_as_sfc %>%
  st_buffer(dist = buffdist / 2) %>% 
  st_as_sf %>%
  st_cast('POINT') %>% 
  rename(geometry = x)

# stamen base map
bsmap1 <- get_stamenmap(bbox = dat_ext, maptype = 'toner-background', zoom = 10)

# change opacity of basemap
mapatt <- attributes(bsmap1)
bsmap1_transparent <- matrix(adjustcolor(bsmap1, 
                                         alpha.f = 0.2), 
                             nrow = nrow(bsmap1))
attributes(bsmap1_transparent) <- mapatt

# plot
map <- ggmap(bsmap1_transparent) +
  geom_sf(data = ppseg, aes(fill = area), color = 'black', inherit.aes = F, alpha = 0.8) +
  geom_sf_text(data = ppseg, aes(label = area), color = 'black', inherit.aes = F, alpha = 0.8, size = 6) +
  scale_fill_manual(values = cols, drop = F) +
  theme(
    legend.title = element_blank(), 
    panel.grid = element_blank(), 
    axis.title = element_blank(), 
    legend.justification = 'top',
    axis.text.y = element_text(size = 8), 
    axis.text.x = element_text(size = 8, angle = 30, hjust = 1),
    panel.background = element_rect(fill = 'white'),
    axis.ticks = element_line(colour = 'grey'),
    panel.border = element_rect(colour = 'grey', fill = NA), 
    legend.position = 'none'
  ) +
  annotation_scale(location = scaleloc) +
  annotation_north_arrow(location = northloc, which_north = "true", height = grid::unit(0.75, "cm"), 
                         width = grid::unit(0.75, "cm"))

map
```

## Water Quality {.tabset .tabset-pills}

### TN

```{r}
wqplo_fun(rswqdat, bswqdat, ppseg, vr = 'tn', cols, logtr = TRUE)
```

### NH3

```{r}
wqplo_fun(rswqdat, bswqdat, ppseg, vr = 'nh34', cols, logtr = TRUE)
```

### TP

```{r}
wqplo_fun(rswqdat, bswqdat, ppseg, vr = 'tp', cols, logtr = TRUE)
```

### Chl

```{r}
wqplo_fun(rswqdat, bswqdat, ppseg, vr = 'chla', cols, logtr = TRUE)
```

### DO Sat.

```{r}
wqplo_fun(rswqdat, bswqdat, ppseg, vr = 'dosat', cols, logtr = FALSE)
```

## Phtyoplankton {.tabset .tabset-pills}

### Mixed algae

```{r}
phyplo_fun(rsphydat, rsphypts, ppseg, vr = 'mixed algae', cols)
```

### Centric diatoms

```{r}
phyplo_fun(rsphydat, rsphypts, ppseg, vr = 'Centric Diatoms', cols)
```

### Bacillariophyta

```{r}
phyplo_fun(rsphydat, rsphypts, ppseg, vr = 'Bacillariophyta', cols)
```

### Karenia brevis

```{r}
phyplo_fun(rsphydat, rsphypts, ppseg, vr = 'Karenia brevis', cols)
```

### Pseudo-nitzschia sp.

```{r}
phyplo_fun(rsphydat, rsphypts, ppseg, vr = 'Pseudo-nitzschia sp.', cols)
```

### Rhizosolenia setigera

```{r}
phyplo_fun(rsphydat, rsphypts, ppseg, vr = 'Rhizosolenia setigera', cols)
```

## Seagrass {.tabset .tabset-pills}

### Overall

```{r}
colpal <- colorRampPalette(RColorBrewer::brewer.pal(n = 8, name = 'Dark2'))
savlevs <- c('Thalassia testudinum', 'Halodule wrightii', 'Syringodium filiforme', 'Ruppia maritima', 'Halophila engelmannii', 'Halophila decipiens')

savsel <- c('Thalassia testudinum', 'Halodule wrightii', 'Syringodium filiforme')

# sort color palette so its the same regardless of species selected
savcol <- colpal(length(savlevs))
names(savcol) <- savlevs
savcol <- savcol[savsel]

# add area
savsum <- savtmp %>% 
  inner_join(rstrnpts, ., by = 'station') %>% 
  st_intersection(ppseg) %>% 
  st_set_geometry(NULL) %>% 
  mutate(
    date = floor_date(date, unit = 'week')
  ) %>% 
  dplyr::group_by(area, date, station, sav_species) %>%
  dplyr::summarise(
    nsites = length(unique(location)),
    bbest = sum(sav_bb, na.rm = T) / nsites
  ) %>% 
  dplyr::group_by(sav_species, date, area) %>%
  dplyr::summarise(
    bbest = mean(bbest, na.rm = T),
    .groups = 'drop'
  ) %>% 
  filter(sav_species %in% savsel)

p1 <- ggplot(savsum, aes(x = date, y = bbest, fill = sav_species)) + 
  geom_area(alpha = 0.8) + 
  facet_grid(~ area, scales = 'free_y') + 
  scale_fill_manual(values = savcol) +
  scale_x_date(expand = c(0, 0)) + 
  theme_minimal(base_size = 14) + 
  labs(
    y = 'Mean abundance (bb)', 
    x = 'Week'
  ) + 
  theme(
    legend.position = 'top', 
    legend.title = element_blank(),
    strip.background = element_blank(), 
    strip.text = element_text(size = 14)
  )

grplevs <- c('Red', 'Green', 'Brown', 'Cyanobacteria')
mcrsel <- grplevs

# sort color palette so its the same regardless of species selected
mcrcol <- c('tomato1', 'lightgreen', 'burlywood3', 'lightblue')
names(mcrcol) <- grplevs
mcrcol <- mcrcol[mcrsel]

mcrsum <- mcrtmp %>% 
  inner_join(rstrnpts, ., by = 'station') %>% 
  st_intersection(ppseg) %>% 
  st_set_geometry(NULL) %>% 
  mutate(
    date = floor_date(date, unit = 'week')
  ) %>% 
  dplyr::group_by(area, date, station, macroalgae_group) %>%
  dplyr::summarise(
    nsites = length(unique(location)),
    bbest = sum(macroalgae_bb, na.rm = T) / nsites
  ) %>% 
  dplyr::group_by(macroalgae_group, date, area) %>%
  dplyr::summarise(
    bbest = mean(bbest, na.rm = T),
    .groups = 'drop'
  ) %>% 
  filter(macroalgae_group %in% mcrsel)

p2 <- ggplot(mcrsum, aes(x = date, y = bbest, fill = macroalgae_group)) + 
  geom_area(alpha = 0.8) + 
  facet_grid(~ area, scales = 'free_y') + 
  scale_fill_manual(values = mcrcol) +
  scale_x_date(expand = c(0, 0)) + 
  theme_minimal(base_size = 14) + 
  labs(
    y = 'Mean abundance (bb)', 
    x = 'Week', 
    caption = 'Results averaged across transects. Note that May 10th, Area 3 was a shift in location from Terra Ceia to Anna Maria/Palma Sola.'  
  ) + 
  theme(
    legend.position = 'top', 
    legend.title = element_blank(),
    strip.background = element_blank(), 
    strip.text = element_text(size = 14)
  )
    
p1 + p2 + plot_layout(ncol = 1)
  
```

### SAV vs macroalgae, by station

```{r}
mcrsel <- c("Red", "Green", "Brown", "Cyanobacteria")
savsel <- c('Thalassia testudinum', 'Halodule wrightii', 'Syringodium filiforme')

# add area
savsum <- savtmp %>% 
  inner_join(rstrnpts, ., by = 'station') %>% 
  st_intersection(ppseg) %>% 
  st_set_geometry(NULL) %>% 
  mutate(
    date = floor_date(date, unit = 'week')
  ) %>% 
  dplyr::group_by(area, date, station, sav_species) %>%
  dplyr::summarise(
    nsites = length(unique(location)),
    bbest = sum(sav_bb, na.rm = T) / nsites
  ) %>% 
  filter(sav_species %in% savsel) %>% 
  group_by(area, date, station) %>% 
  summarize(
    savbbest = mean(bbest)
  )

mcrsum <- mcrtmp %>% 
  inner_join(rstrnpts, ., by = 'station') %>% 
  st_intersection(ppseg) %>% 
  st_set_geometry(NULL) %>% 
  mutate(
    date = floor_date(date, unit = 'week')
  ) %>% 
  dplyr::group_by(area, date, station, macroalgae_group) %>%
  dplyr::summarise(
    nsites = length(unique(location)),
    bbest = sum(macroalgae_bb, na.rm = T) / nsites
  ) %>% 
  filter(macroalgae_group %in% mcrsel) %>% 
  group_by(area, date, station) %>% 
  summarize(
    mcrbbest = mean(bbest)
  )

toplo <- full_join(mcrsum, savsum, by = c('area', 'station', 'date')) %>% 
  mutate(
    mo = month(date,label = T)
  )

ggplot(toplo, aes(x = mcrbbest, y = savbbest)) + 
  geom_point(aes(fill = mo), colour = 'grey', pch = 21, size = 3) +
  facet_grid(~ area, scales = 'free') +
  theme_minimal(base_size = 14) + 
  geom_smooth() +
  coord_cartesian(ylim = c(0, NA)) +
  labs(
    y = 'SAV mean abundance (bb)',
    x = 'Macroalgae mean abundance (bb)', 
    caption = 'Results retained by transect'
  ) +
  theme(
    legend.position = 'top', 
    legend.title = element_blank(),
    strip.background = element_blank(), 
    strip.text = element_text(size = 14)
  )
```

### Water quality vs macroalgae vs SAV

```{r}
nonbay <- c('BH01', 'P Port 2', 'P Port 3', 'PM Out', '20120409-01', 'PPC41', 'P Port 4', 'PMB01', 'NGS-S Pond')

# add area
savsum <- savtmp %>% 
  inner_join(rstrnpts, ., by = 'station') %>% 
  st_intersection(ppseg) %>% 
  st_set_geometry(NULL) %>% 
  # mutate(
  #   date = floor_date(date, unit = 'week')
  # ) %>% 
  dplyr::group_by(area, date, station, sav_species) %>%
  dplyr::summarise(
    nsites = length(unique(location)),
    bbest = sum(sav_bb, na.rm = T) / nsites
  ) %>% 
  filter(sav_species %in% savsel) %>% 
  dplyr::group_by(date, area) %>%
  dplyr::summarise(
    savbbest = mean(bbest, na.rm = T),
    .groups = 'drop'
  ) 

mcrsum <- mcrtmp %>% 
  inner_join(rstrnpts, ., by = 'station') %>% 
  st_intersection(ppseg) %>% 
  st_set_geometry(NULL) %>% 
  # mutate(
  #   date = floor_date(date, unit = 'week')
  # ) %>% 
  dplyr::group_by(area, date, station, macroalgae_group) %>%
  dplyr::summarise(
    nsites = length(unique(location)),
    bbest = sum(macroalgae_bb, na.rm = T) / nsites
  ) %>% 
  filter(macroalgae_group %in% mcrsel) %>% 
  dplyr::group_by(date, area) %>%
  dplyr::summarise(
    mcrbbest = mean(bbest, na.rm = T),
    .groups = 'drop'
  ) 

rswqtmp <- rswqdat %>% 
  filter(var %in%  c('tn', 'nh34', 'chla', 'tp')) %>% 
  filter(!station %in% nonbay) %>% 
  inner_join(rsstatloc, ., by = c('station', 'source')) %>% 
  st_intersection(ppseg) %>% 
  st_set_geometry(NULL) %>% 
  select(-qual, -bswqstation, -nrmrng, -source, -source_lng, -uni, -lbunis, -comment) %>% 
  # mutate(
  #   date = floor_date(date, unit = 'week')
  # ) %>% 
  group_by(date, area, var) %>% 
  summarise(
    val = mean(log(val)), 
    val = exp(val)
    ) %>% 
  spread(var, val)

toplo <- full_join(mcrsum, savsum, by = c('area', 'date')) %>% 
  inner_join(rswqtmp, by = c('area', 'date')) %>% 
  mutate(
    mo = month(date,label = T)
  )

bssz <- 14

mod1 <- summary(lm(chla ~ tn, toplo))
txt <- paste0('Slope ', round(coefficients(mod1)[2, 1], 2), ', R2 ', round(mod1$r.squared, 2), ', pval ', round(coefficients(mod1)[2, 4], 3))
p1 <- ggplot(toplo, aes(x = tn, y = chla)) + 
  geom_point(aes(fill = mo), colour = 'grey', size = 3, pch = 21) + 
  geom_smooth(method = 'lm') + 
  labs(
    x = 'Area averaged TN (mg/L)', 
    y = 'Area averaged Chla (ug/L)', 
    subtitle = txt, 
    title = 'Chla ~ TN'
  ) +
  theme_minimal(base_family = bssz)

mod2 <- summary(lm(mcrbbest ~ tn, toplo))
txt <- paste0('Slope ', round(coefficients(mod2)[2, 1], 2), ', R2 ', round(mod2$r.squared, 2), ', pval ', round(coefficients(mod2)[2, 4], 3))
p2 <- ggplot(toplo, aes(x = tn, y = mcrbbest)) + 
  geom_point(aes(fill = mo), colour = 'grey', size = 3, pch = 21) + 
  geom_smooth(method = 'lm') + 
  labs(
    x = 'Area averaged TN (mg/L)', 
    y = 'Area averaged macroalgae abundance', 
    subtitle = txt, 
    title = 'Macroalgae ~ TN'
  ) +
  theme_minimal(base_family = bssz)

mod3 <- summary(lm(savbbest ~ mcrbbest, toplo))
txt <- paste0('Slope ', round(coefficients(mod3)[2, 1], 2), ', R2 ', round(mod3$r.squared, 2), ', pval ', round(coefficients(mod3)[2, 4], 3))
p3 <- ggplot(toplo, aes(x = mcrbbest, y = savbbest)) +
  geom_point(aes(fill = mo), colour = 'grey', size = 3, pch = 21) +
  geom_smooth(method = 'lm') +
  labs(
    x = 'Area averaged macroalgae abundance',
    y = 'Area averaged SAV abundance',
    subtitle = txt,
    title = 'SAV ~ Macroalgae'
  ) +
  theme_minimal(base_family = bssz)


# mod4 <- summary(lm(chla ~ nh34, toplo))
# txt <- paste0('Slope ', round(coefficients(mod4)[2, 1], 2), ', R2 ', round(mod4$r.squared, 2), ', pval ', round(coefficients(mod1)[2, 4], 3))
# p4 <- ggplot(toplo, aes(x = nh34, y = chla)) + 
#   geom_point(aes(fill = mo), colour = 'grey', size = 3, pch = 21) + 
#   geom_smooth(method = 'lm') + 
#   labs(
#     x = 'Area averaged NH3 (mg/L)', 
#     y = 'Area averaged Chla (ug/L)', 
#     subtitle = txt, 
#     title = 'Chla ~ NH3'
#   ) +
#   theme_minimal(base_family = bssz)
# 
# mod5 <- summary(lm(mcrbbest ~ nh34, toplo))
# txt <- paste0('Slope ', round(coefficients(mod5)[2, 1], 2), ', R2 ', round(mod5$r.squared, 2), ', pval ', round(coefficients(mod5)[2, 4], 3))
# p5 <- ggplot(toplo, aes(x = nh34, y = mcrbbest)) + 
#   geom_point(aes(fill = mo), colour = 'grey', size = 3, pch = 21) + 
#   geom_smooth(method = 'lm') + 
#   labs(
#     x = 'Area averaged NH3 (mg/L)', 
#     y = 'Area averaged macroalgae abundance', 
#     subtitle = txt, 
#     title = 'Macroalgae ~ NH3'
#   ) +
#   theme_minimal(base_family = bssz)
# 
# mod6 <- summary(lm(savbbest ~ mcrbbest, toplo))
# txt <- paste0('Slope ', round(coefficients(mod6)[2, 1], 2), ', R2 ', round(mod6$r.squared, 2), ', pval ', round(coefficients(mod6)[2, 4], 3))
# p6 <- ggplot(toplo, aes(x = mcrbbest, y = savbbest)) + 
#   geom_point(aes(fill = mo), colour = 'grey', size = 3, pch = 21) + 
#   geom_smooth(method = 'lm') + 
#   labs(
#     x = 'Area averaged macroalgae abundance', 
#     y = 'Area averaged SAV abundance', 
#     subtitle = txt, 
#     title = 'SAV ~ Macroalgae'
#   ) +
#   theme_minimal(base_family = bssz)  

p1 + p2 + p3 + plot_layout(ncol = 3, guides = 'collect') & 
  theme(
    legend.position = 'top', 
    legend.title = element_blank()
  )
```

