library(dplyr)
library(tidyr)
library(here)

load(file = here('data/rswqdat.RData'))
load(file = here('data/rsstatloc.RData'))
load(file = here('data/parms.RData'))
load(file = here('data/rstrndat.RData'))
load(file = here('data/rstrnpts.RData'))
load(file = here('data/rscntdat.RData'))
load(file = here('data/rsphydat.RData'))
load(file = here('data/rsphypts.RData'))
load(file = here('data/rscntthr.RData'))
load(file = here('data/rsallpts.RData'))
load(file = here('data/rstrnwts.RData'))
load(file = here('data/bstransect.RData'))
load(file = here('data/rsbntdat.RData'))
load(file = here('data/rsbntpts.RData'))