on:
  push:
    branches:
      - main
      - master
    
name: databuild 

jobs:
  render:
    name: databuild
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          packages: |
            any::dplyr
            any::here
            any::testthat
            any::tidyr
      
      - name: Run tests
        run: Rscript -e "library(testthat); testthat::test_dir('tests/testthat', reporter = c('progress', 'fail'))"
